import React, { useState } from 'react';
import { Download, Copy, Check, FileText, X } from 'lucide-react';

export default function ReportExportModal({ 
  isOpen, 
  onClose, 
  formData, 
  bmi, 
  bmiCat, 
  bpCat, 
  predictionResult, 
  recommendations, 
  theme 
}) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const now = new Date();
  const dateStr = now.toISOString().replace('T', ' ').substring(0, 19);
  const fileDate = now.toISOString().substring(0, 10).replace(/-/g, '');

  const probPct = predictionResult ? predictionResult.probability_pct : 50;
  const isHigh = predictionResult ? predictionResult.is_high_risk : false;

  const reportContent = `====================================================
CARDIORISK AI - CARDIOVASCULAR HEALTH ASSESSMENT
Date Generated: ${dateStr}
====================================================

PATIENT BIOMETRIC PROFILE:
----------------------------------------------------
- Age: ${formData.age} years
- Biological Sex: ${formData.gender === 2 || formData.gender === "Male" ? 'Male' : 'Female'}
- Height: ${formData.height} cm
- Weight: ${formData.weight} kg
- Body Mass Index (BMI): ${bmi} kg/m² (${bmiCat.label})

HEMODYNAMICS & BIOCHEMICAL READINGS:
----------------------------------------------------
- Systolic Blood Pressure: ${formData.ap_hi} mmHg
- Diastolic Blood Pressure: ${formData.ap_lo} mmHg
- Blood Pressure Classification: ${bpCat.label}
- Cholesterol Level: ${formData.cholesterol === 3 || formData.cholesterol === "Well Above Normal" ? "Well Above Normal" : formData.cholesterol === 2 || formData.cholesterol === "Above Normal" ? "Above Normal" : "Normal"}
- Glucose Level: ${formData.gluc === 3 || formData.gluc === "Well Above Normal" ? "Well Above Normal" : formData.gluc === 2 || formData.gluc === "Above Normal" ? "Above Normal" : "Normal"}

LIFESTYLE FACTORS:
----------------------------------------------------
- Smoking: ${formData.smoke === 1 || formData.smoke === "Yes" ? "Yes" : "No"}
- Alcohol Intake: ${formData.alco === 1 || formData.alco === "Yes" ? "Yes" : "No"}
- Physically Active: ${formData.active === 1 || formData.active === "Yes" ? "Yes" : "No"}

CARDIOVASCULAR RISK EVALUATION:
----------------------------------------------------
- Risk Classification: ${isHigh ? 'HIGH RISK' : 'LOW RISK'}
- Predicted Risk Probability: ${probPct.toFixed(2)}%

RECOMMENDED ACTION PLAN:
----------------------------------------------------
${recommendations.map(r => `- ${r.replace(/\*\*/g, '')}`).join('\n')}

====================================================
Disclaimer: This report is generated by a Machine Learning model for educational and preliminary screening purposes. It does not replace professional medical diagnosis.
====================================================`;

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([reportContent], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `cardio_risk_assessment_${fileDate}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(reportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-in fade-in duration-200">
      <div 
        className="w-full max-w-2xl rounded-2xl border p-6 flex flex-col max-h-[90vh] shadow-2xl"
        style={{
          backgroundColor: theme.bg_secondary,
          borderColor: theme.card_border,
          color: theme.text_primary
        }}
      >
        {/* Modal Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-700/40">
          <div className="flex items-center gap-3">
            <div 
              className="p-2.5 rounded-xl text-white font-bold"
              style={{ background: theme.accent_gradient }}
            >
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="font-extrabold text-lg" style={{ color: theme.text_primary }}>
                Export Patient Health Summary Report
              </h3>
              <p className="text-xs font-medium" style={{ color: theme.text_secondary }}>
                Clinical assessment documentation ready for archival or patient consult.
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body: Monospace Text Preview */}
        <div className="flex-1 my-4 overflow-y-auto">
          <textarea
            readOnly
            value={reportContent}
            rows={14}
            className="w-full p-4 rounded-xl font-mono text-xs leading-relaxed border resize-none focus:outline-none"
            style={{
              backgroundColor: theme.input_bg,
              borderColor: theme.input_border,
              color: theme.input_text
            }}
          />
        </div>

        {/* Modal Actions */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-3 border-t border-slate-700/40">
          <button
            type="button"
            onClick={handleCopy}
            className="w-full sm:w-auto px-4 py-2.5 rounded-xl border text-xs font-bold flex items-center justify-center gap-2 hover:bg-slate-800 transition-all cursor-pointer"
            style={{ borderColor: theme.input_border, color: theme.text_primary }}
          >
            {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? "Copied to Clipboard!" : "Copy Raw Text"}</span>
          </button>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              type="button"
              onClick={onClose}
              className="w-1/2 sm:w-auto px-4 py-2.5 rounded-xl text-xs font-bold hover:bg-slate-800 transition-colors cursor-pointer"
              style={{ color: theme.text_secondary }}
            >
              Close
            </button>
            <button
              type="button"
              onClick={handleDownload}
              className="w-1/2 sm:w-auto theme-btn-primary px-5 py-2.5 text-xs font-extrabold flex items-center justify-center gap-2 cursor-pointer"
            >
              <Download className="w-4 h-4" />
              <span>Download Report (.txt)</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
